name: 'Terraform plan'

inputs:
  environment:
    required: true
  work_dir:
    required: true
  additional_tf_vars:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Terraform plan
      id: terraform_plan
      working-directory: ${{ inputs.work_dir }}
      run: |
        terraform plan -input=false \
          -var-file="tfvars/${{ inputs.environment }}/main.tfvars" \
          ${{ additional_tf_vars }} \
          -out ${{ github.run_number }}.tfplan
    
    - name: Publish Terraform Plan
      working-directory: ${{ inputs.work_dir }}
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ${{ inputs.work_dir }}/${{ github.run_number }}.tfplan