name: 'Terraform plan'

inputs:
  backend_azure_resource_group_name:
    required: true
  backend_azure_storage_account_name:
    required: true
  backend_container_name:
    required: true
  environment:
    required: true
  work_dir:
    required: true
  additional_tf_vars:
    required: false
    default: ""

runs:
  using: "composite"
  steps:


    - name: Symlink current Actions repo
      env:
        GH_ACTION_REPO: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}
      shell: bash
      run: ln -s /home/runner/work/_actions/$GH_ACTION_REPO/$GH_ACTION_REF/  /home/runner/work/_actions/current

    - name: Symlink current Actions repo
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        pwd
        ls ./../../_actions/current/..
        
    # - name: Terraform init
    #   uses: ../terraform_init
    #   with:
    #     backend_azure_resource_group_name: ${{ inputs.backend_azure_resource_group_name }}
    #     backend_azure_storage_account_name: ${{ inputs.backend_azure_storage_account_name }}
    #     backend_container_name: ${{ inputs.backend_container_name }}
    #     work_dir: ${{ inputs.work_dir }}

    - name: Terraform Validate
      working-directory: ${{ inputs.work_dir }}
      shell: bash
      run: terraform validate

    - name: Terraform plan
      working-directory: ${{ inputs.work_dir }}
      shell: bash
      run: |
        terraform plan -input=false \
          -var-file="tfvars/${{ inputs.environment }}/main.tfvars" \
          ${{ inputs.additional_tf_vars }} \
          -out ${{ github.run_number }}.tfplan
    
    - name: Publish Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ${{ inputs.work_dir }}/${{ github.run_number }}.tfplan